/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.BioData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BioData', function() {
    it('should create an instance of BioData', function() {
      // uncomment below and update the code to test BioData
      //var instance = new Pim.BioData();
      //expect(instance).to.be.a(Pim.BioData);
    });

    it('should have the property initial (base name: "Initial")', function() {
      // uncomment below and update the code to test the property initial
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property employeeId (base name: "EmployeeId")', function() {
      // uncomment below and update the code to test the property employeeId
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "Gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property dateOfBirth (base name: "DateOfBirth")', function() {
      // uncomment below and update the code to test the property dateOfBirth
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property countryOfBirth (base name: "CountryOfBirth")', function() {
      // uncomment below and update the code to test the property countryOfBirth
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property provinceOfBirth (base name: "ProvinceOfBirth")', function() {
      // uncomment below and update the code to test the property provinceOfBirth
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property nationality (base name: "Nationality")', function() {
      // uncomment below and update the code to test the property nationality
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property nationalID (base name: "NationalID")', function() {
      // uncomment below and update the code to test the property nationalID
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property maritalStatus (base name: "MaritalStatus")', function() {
      // uncomment below and update the code to test the property maritalStatus
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

    it('should have the property profilePhoto (base name: "ProfilePhoto")', function() {
      // uncomment below and update the code to test the property profilePhoto
      //var instance = new Pim.BioData();
      //expect(instance).to.be();
    });

  });

}));
