/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.BioDataApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BioDataApi', function() {
    describe('createBioData', function() {
      it('should call createBioData successfully', function(done) {
        //uncomment below and update the code to test createBioData
        //instance.createBioData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBioData', function() {
      it('should call deleteBioData successfully', function(done) {
        //uncomment below and update the code to test deleteBioData
        //instance.deleteBioData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBioData', function() {
      it('should call getBioData successfully', function(done) {
        //uncomment below and update the code to test getBioData
        //instance.getBioData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBioData', function() {
      it('should call listBioData successfully', function(done) {
        //uncomment below and update the code to test listBioData
        //instance.listBioData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsBioData', function() {
      it('should call optionsBioData successfully', function(done) {
        //uncomment below and update the code to test optionsBioData
        //instance.optionsBioData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsBioDataId', function() {
      it('should call optionsBioDataId successfully', function(done) {
        //uncomment below and update the code to test optionsBioDataId
        //instance.optionsBioDataId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBioData', function() {
      it('should call updateBioData successfully', function(done) {
        //uncomment below and update the code to test updateBioData
        //instance.updateBioData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
