/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.ComputerLiteracyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ComputerLiteracyApi', function() {
    describe('createComputerLiteracy', function() {
      it('should call createComputerLiteracy successfully', function(done) {
        //uncomment below and update the code to test createComputerLiteracy
        //instance.createComputerLiteracy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteComputerLiteracy', function() {
      it('should call deleteComputerLiteracy successfully', function(done) {
        //uncomment below and update the code to test deleteComputerLiteracy
        //instance.deleteComputerLiteracy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getComputerLiteracy', function() {
      it('should call getComputerLiteracy successfully', function(done) {
        //uncomment below and update the code to test getComputerLiteracy
        //instance.getComputerLiteracy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listComputerLiteracies', function() {
      it('should call listComputerLiteracies successfully', function(done) {
        //uncomment below and update the code to test listComputerLiteracies
        //instance.listComputerLiteracies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsComputerLiteracies', function() {
      it('should call optionsComputerLiteracies successfully', function(done) {
        //uncomment below and update the code to test optionsComputerLiteracies
        //instance.optionsComputerLiteracies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsComputerLiteracyId', function() {
      it('should call optionsComputerLiteracyId successfully', function(done) {
        //uncomment below and update the code to test optionsComputerLiteracyId
        //instance.optionsComputerLiteracyId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateComputerLiteracy', function() {
      it('should call updateComputerLiteracy successfully', function(done) {
        //uncomment below and update the code to test updateComputerLiteracy
        //instance.updateComputerLiteracy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
