/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.EducationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EducationApi', function() {
    describe('createEducation', function() {
      it('should call createEducation successfully', function(done) {
        //uncomment below and update the code to test createEducation
        //instance.createEducation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEducation', function() {
      it('should call deleteEducation successfully', function(done) {
        //uncomment below and update the code to test deleteEducation
        //instance.deleteEducation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEducation', function() {
      it('should call getEducation successfully', function(done) {
        //uncomment below and update the code to test getEducation
        //instance.getEducation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listEducations', function() {
      it('should call listEducations successfully', function(done) {
        //uncomment below and update the code to test listEducations
        //instance.listEducations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsEducationId', function() {
      it('should call optionsEducationId successfully', function(done) {
        //uncomment below and update the code to test optionsEducationId
        //instance.optionsEducationId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsEducations', function() {
      it('should call optionsEducations successfully', function(done) {
        //uncomment below and update the code to test optionsEducations
        //instance.optionsEducations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEducation', function() {
      it('should call updateEducation successfully', function(done) {
        //uncomment below and update the code to test updateEducation
        //instance.updateEducation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
