/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.LanguageApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LanguageApi', function() {
    describe('createLanguage', function() {
      it('should call createLanguage successfully', function(done) {
        //uncomment below and update the code to test createLanguage
        //instance.createLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLanguage', function() {
      it('should call deleteLanguage successfully', function(done) {
        //uncomment below and update the code to test deleteLanguage
        //instance.deleteLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLanguage', function() {
      it('should call getLanguage successfully', function(done) {
        //uncomment below and update the code to test getLanguage
        //instance.getLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listLanguages', function() {
      it('should call listLanguages successfully', function(done) {
        //uncomment below and update the code to test listLanguages
        //instance.listLanguages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsLanguageId', function() {
      it('should call optionsLanguageId successfully', function(done) {
        //uncomment below and update the code to test optionsLanguageId
        //instance.optionsLanguageId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsLanguages', function() {
      it('should call optionsLanguages successfully', function(done) {
        //uncomment below and update the code to test optionsLanguages
        //instance.optionsLanguages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLanguage', function() {
      it('should call updateLanguage successfully', function(done) {
        //uncomment below and update the code to test updateLanguage
        //instance.updateLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
