/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExecutiveSummary model module.
 * @module model/ExecutiveSummary
 * @version 1.0.0
 */
class ExecutiveSummary {
    /**
     * Constructs a new <code>ExecutiveSummary</code>.
     * Represent an executive summaries of employee.
     * @alias module:model/ExecutiveSummary
     * @param employeeId {String} 
     */
    constructor(employeeId) { 
        
        ExecutiveSummary.initialize(this, employeeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, employeeId) { 
        obj['EmployeeId'] = employeeId;
    }

    /**
     * Constructs a <code>ExecutiveSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExecutiveSummary} obj Optional instance to populate.
     * @return {module:model/ExecutiveSummary} The populated <code>ExecutiveSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExecutiveSummary();

            if (data.hasOwnProperty('EmployeeId')) {
                obj['EmployeeId'] = ApiClient.convertToType(data['EmployeeId'], 'String');
            }
            if (data.hasOwnProperty('Summary')) {
                obj['Summary'] = ApiClient.convertToType(data['Summary'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExecutiveSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExecutiveSummary</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExecutiveSummary.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['EmployeeId'] && !(typeof data['EmployeeId'] === 'string' || data['EmployeeId'] instanceof String)) {
            throw new Error("Expected the field `EmployeeId` to be a primitive type in the JSON string but got " + data['EmployeeId']);
        }
        // ensure the json data is a string
        if (data['Summary'] && !(typeof data['Summary'] === 'string' || data['Summary'] instanceof String)) {
            throw new Error("Expected the field `Summary` to be a primitive type in the JSON string but got " + data['Summary']);
        }

        return true;
    }


}

ExecutiveSummary.RequiredProperties = ["EmployeeId"];

/**
 * @member {String} EmployeeId
 */
ExecutiveSummary.prototype['EmployeeId'] = undefined;

/**
 * @member {String} Summary
 */
ExecutiveSummary.prototype['Summary'] = undefined;






export default ExecutiveSummary;

