/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BioDataNamePrimaryName from './BioDataNamePrimaryName';

/**
 * The BioDataName model module.
 * @module model/BioDataName
 * @version 1.0.0
 */
class BioDataName {
    /**
     * Constructs a new <code>BioDataName</code>.
     * @alias module:model/BioDataName
     */
    constructor() { 
        
        BioDataName.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BioDataName</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BioDataName} obj Optional instance to populate.
     * @return {module:model/BioDataName} The populated <code>BioDataName</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BioDataName();

            if (data.hasOwnProperty('PrimaryName')) {
                obj['PrimaryName'] = BioDataNamePrimaryName.constructFromObject(data['PrimaryName']);
            }
            if (data.hasOwnProperty('SecondaryName')) {
                obj['SecondaryName'] = BioDataNamePrimaryName.constructFromObject(data['SecondaryName']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BioDataName</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BioDataName</code>.
     */
    static validateJSON(data) {
        // validate the optional field `PrimaryName`
        if (data['PrimaryName']) { // data not null
          BioDataNamePrimaryName.validateJSON(data['PrimaryName']);
        }
        // validate the optional field `SecondaryName`
        if (data['SecondaryName']) { // data not null
          BioDataNamePrimaryName.validateJSON(data['SecondaryName']);
        }

        return true;
    }


}



/**
 * @member {module:model/BioDataNamePrimaryName} PrimaryName
 */
BioDataName.prototype['PrimaryName'] = undefined;

/**
 * @member {module:model/BioDataNamePrimaryName} SecondaryName
 */
BioDataName.prototype['SecondaryName'] = undefined;






export default BioDataName;

