/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoreCompetency model module.
 * @module model/CoreCompetency
 * @version 1.0.0
 */
class CoreCompetency {
    /**
     * Constructs a new <code>CoreCompetency</code>.
     * Represent an core competency of employee.
     * @alias module:model/CoreCompetency
     * @param employeeId {String} 
     */
    constructor(employeeId) { 
        
        CoreCompetency.initialize(this, employeeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, employeeId) { 
        obj['EmployeeId'] = employeeId;
    }

    /**
     * Constructs a <code>CoreCompetency</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoreCompetency} obj Optional instance to populate.
     * @return {module:model/CoreCompetency} The populated <code>CoreCompetency</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoreCompetency();

            if (data.hasOwnProperty('EmployeeId')) {
                obj['EmployeeId'] = ApiClient.convertToType(data['EmployeeId'], 'String');
            }
            if (data.hasOwnProperty('Competency')) {
                obj['Competency'] = ApiClient.convertToType(data['Competency'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CoreCompetency</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CoreCompetency</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CoreCompetency.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['EmployeeId'] && !(typeof data['EmployeeId'] === 'string' || data['EmployeeId'] instanceof String)) {
            throw new Error("Expected the field `EmployeeId` to be a primitive type in the JSON string but got " + data['EmployeeId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['Competency'])) {
            throw new Error("Expected the field `Competency` to be an array in the JSON data but got " + data['Competency']);
        }

        return true;
    }


}

CoreCompetency.RequiredProperties = ["EmployeeId"];

/**
 * @member {String} EmployeeId
 */
CoreCompetency.prototype['EmployeeId'] = undefined;

/**
 * @member {Array.<String>} Competency
 */
CoreCompetency.prototype['Competency'] = undefined;






export default CoreCompetency;

