/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.Education();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Education', function() {
    it('should create an instance of Education', function() {
      // uncomment below and update the code to test Education
      //var instance = new Pim.Education();
      //expect(instance).to.be.a(Pim.Education);
    });

    it('should have the property employeeId (base name: "EmployeeId")', function() {
      // uncomment below and update the code to test the property employeeId
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property fromYear (base name: "FromYear")', function() {
      // uncomment below and update the code to test the property fromYear
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property toYear (base name: "ToYear")', function() {
      // uncomment below and update the code to test the property toYear
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property school (base name: "School")', function() {
      // uncomment below and update the code to test the property school
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property degree (base name: "Degree")', function() {
      // uncomment below and update the code to test the property degree
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property fieldOfStudy (base name: "FieldOfStudy")', function() {
      // uncomment below and update the code to test the property fieldOfStudy
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property major (base name: "Major")', function() {
      // uncomment below and update the code to test the property major
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property achievements (base name: "Achievements")', function() {
      // uncomment below and update the code to test the property achievements
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

    it('should have the property remarks (base name: "Remarks")', function() {
      // uncomment below and update the code to test the property remarks
      //var instance = new Pim.Education();
      //expect(instance).to.be();
    });

  });

}));
