/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.Training();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Training', function() {
    it('should create an instance of Training', function() {
      // uncomment below and update the code to test Training
      //var instance = new Pim.Training();
      //expect(instance).to.be.a(Pim.Training);
    });

    it('should have the property employeeId (base name: "EmployeeId")', function() {
      // uncomment below and update the code to test the property employeeId
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property courseTitle (base name: "CourseTitle")', function() {
      // uncomment below and update the code to test the property courseTitle
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property organizer (base name: "Organizer")', function() {
      // uncomment below and update the code to test the property organizer
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property fromDate (base name: "FromDate")', function() {
      // uncomment below and update the code to test the property fromDate
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property toDate (base name: "ToDate")', function() {
      // uncomment below and update the code to test the property toDate
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property numberOfDays (base name: "NumberOfDays")', function() {
      // uncomment below and update the code to test the property numberOfDays
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "Location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property achievement (base name: "Achievement")', function() {
      // uncomment below and update the code to test the property achievement
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

    it('should have the property remarks (base name: "Remarks")', function() {
      // uncomment below and update the code to test the property remarks
      //var instance = new Pim.Training();
      //expect(instance).to.be();
    });

  });

}));
