/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.CoreCompetencyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CoreCompetencyApi', function() {
    describe('createCoreCompetency', function() {
      it('should call createCoreCompetency successfully', function(done) {
        //uncomment below and update the code to test createCoreCompetency
        //instance.createCoreCompetency(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCoreCompetency', function() {
      it('should call deleteCoreCompetency successfully', function(done) {
        //uncomment below and update the code to test deleteCoreCompetency
        //instance.deleteCoreCompetency(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCoreCompetency', function() {
      it('should call getCoreCompetency successfully', function(done) {
        //uncomment below and update the code to test getCoreCompetency
        //instance.getCoreCompetency(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCoreCompetencies', function() {
      it('should call listCoreCompetencies successfully', function(done) {
        //uncomment below and update the code to test listCoreCompetencies
        //instance.listCoreCompetencies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsCoreCompetencies', function() {
      it('should call optionsCoreCompetencies successfully', function(done) {
        //uncomment below and update the code to test optionsCoreCompetencies
        //instance.optionsCoreCompetencies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsCoreCompetencyId', function() {
      it('should call optionsCoreCompetencyId successfully', function(done) {
        //uncomment below and update the code to test optionsCoreCompetencyId
        //instance.optionsCoreCompetencyId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCoreCompetency', function() {
      it('should call updateCoreCompetency successfully', function(done) {
        //uncomment below and update the code to test updateCoreCompetency
        //instance.updateCoreCompetency(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
