/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.ExecutiveSummaryApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExecutiveSummaryApi', function() {
    describe('createExecutiveSummary', function() {
      it('should call createExecutiveSummary successfully', function(done) {
        //uncomment below and update the code to test createExecutiveSummary
        //instance.createExecutiveSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteExecutiveSummary', function() {
      it('should call deleteExecutiveSummary successfully', function(done) {
        //uncomment below and update the code to test deleteExecutiveSummary
        //instance.deleteExecutiveSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getExecutiveSummary', function() {
      it('should call getExecutiveSummary successfully', function(done) {
        //uncomment below and update the code to test getExecutiveSummary
        //instance.getExecutiveSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listExecutiveSummaries', function() {
      it('should call listExecutiveSummaries successfully', function(done) {
        //uncomment below and update the code to test listExecutiveSummaries
        //instance.listExecutiveSummaries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsExecutiveSummaries', function() {
      it('should call optionsExecutiveSummaries successfully', function(done) {
        //uncomment below and update the code to test optionsExecutiveSummaries
        //instance.optionsExecutiveSummaries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsExecutiveSummaryId', function() {
      it('should call optionsExecutiveSummaryId successfully', function(done) {
        //uncomment below and update the code to test optionsExecutiveSummaryId
        //instance.optionsExecutiveSummaryId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateExecutiveSummary', function() {
      it('should call updateExecutiveSummary successfully', function(done) {
        //uncomment below and update the code to test updateExecutiveSummary
        //instance.updateExecutiveSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
