/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.TrainingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrainingApi', function() {
    describe('createTraining', function() {
      it('should call createTraining successfully', function(done) {
        //uncomment below and update the code to test createTraining
        //instance.createTraining(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTraining', function() {
      it('should call deleteTraining successfully', function(done) {
        //uncomment below and update the code to test deleteTraining
        //instance.deleteTraining(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTraining', function() {
      it('should call getTraining successfully', function(done) {
        //uncomment below and update the code to test getTraining
        //instance.getTraining(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listTrainings', function() {
      it('should call listTrainings successfully', function(done) {
        //uncomment below and update the code to test listTrainings
        //instance.listTrainings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsTrainingId', function() {
      it('should call optionsTrainingId successfully', function(done) {
        //uncomment below and update the code to test optionsTrainingId
        //instance.optionsTrainingId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsTrainings', function() {
      it('should call optionsTrainings successfully', function(done) {
        //uncomment below and update the code to test optionsTrainings
        //instance.optionsTrainings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTraining', function() {
      it('should call updateTraining successfully', function(done) {
        //uncomment below and update the code to test updateTraining
        //instance.updateTraining(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
