/**
 * pim
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Pim);
  }
}(this, function(expect, Pim) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Pim.WorkExperienceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WorkExperienceApi', function() {
    describe('createWorkExperience', function() {
      it('should call createWorkExperience successfully', function(done) {
        //uncomment below and update the code to test createWorkExperience
        //instance.createWorkExperience(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteWorkExperience', function() {
      it('should call deleteWorkExperience successfully', function(done) {
        //uncomment below and update the code to test deleteWorkExperience
        //instance.deleteWorkExperience(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWorkExperience', function() {
      it('should call getWorkExperience successfully', function(done) {
        //uncomment below and update the code to test getWorkExperience
        //instance.getWorkExperience(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listWorkExperiences', function() {
      it('should call listWorkExperiences successfully', function(done) {
        //uncomment below and update the code to test listWorkExperiences
        //instance.listWorkExperiences(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsWorkExperienceId', function() {
      it('should call optionsWorkExperienceId successfully', function(done) {
        //uncomment below and update the code to test optionsWorkExperienceId
        //instance.optionsWorkExperienceId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('optionsWorkExperiences', function() {
      it('should call optionsWorkExperiences successfully', function(done) {
        //uncomment below and update the code to test optionsWorkExperiences
        //instance.optionsWorkExperiences(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateWorkExperience', function() {
      it('should call updateWorkExperience successfully', function(done) {
        //uncomment below and update the code to test updateWorkExperience
        //instance.updateWorkExperience(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
